name = "tokobuku-v2"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static Assets Routing
[assets]
directory = "."
binding = "ASSETS"

# Native Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "gudangbuku"
database_id = "1d3acb61-827e-45bb-9e6a-76cd265ff677"
